<?php
// disable error reporting for production code
error_reporting(E_ALL);
ini_set('display_errors', TRUE);

// Start session
//if ((session_status() == PHP_SESSION_NONE) || (session_status() !== PHP_SESSION_ACTIVE)) {
	session_name("GalleryBuilder");
	//if(isset($_COOKIE['GalleryBuilder'])) {
	//	session_id($_COOKIE['GalleryBuilder']);}
	require_once("/home/bitnami/session2DB/Zebra.php");
//}

// be sure we are here by a POST request
if (($_SERVER["REQUEST_METHOD"] == "POST") && (isset($_POST['galleryname'])) && ($_POST['galleryname'] != '')) {
$galleryname = trim($_POST['galleryname']);
$Galleries = '/home/bitnami/Galleries/htdocs/';
// set up to buffer output
ob_start();
// begin generated web page content
$head1 = <<< EOT1
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
EOT1;
echo $head1;
echo '<title>'.$_SESSION['pagetitle'].'</title>';
$head2 = <<< EOT2
	<meta name="description" content="Web Image Gallery Generated by IsoBlock Synthetic Reality Gallery Builder">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
EOT2;
echo $head2;
echo '<meta NAME="Last-Modified" CONTENT="'. date ("F d Y H:i:s.", getlastmod()).'">';
echo '<meta name="copyright" content="Site design and code Copyright 2019 by IsoBlock.com, Content is Copyright 2019 by '.$_SESSION['artistname'].'">';
$head3 = <<< EOT3
	<meta name="author" content="Bob Wright">
	<meta name="keywords" content="images,art,graphics,illustration">
	<meta name="rating" content="general">
	<meta name="robots" content="index, follow"/> 
EOT3;
echo $head3;
//if($_SESSION['siteurl'] != "") {
//echo '<base href="'.$_SESSION['siteurl'].'">';
//} else {
echo '<base href="./">';
//}
if($_SESSION['siteurl'] != "./") {
echo '	<link href="'.$_SESSION['siteurl'].'" rel="canonical">';
//echo '	<link href="'.$_SESSION['canonicalurl'].'" rel="canonical">';
}
$head4 = <<< EOT4
	<link href="/Galleries/css/normalize.css" media="screen" rel="stylesheet" type="text/css"/>
    <!--    <link href="/Galleries/css/main.css" rel="stylesheet"> -->
	<link href="/Galleries/css/SiteFonts.css" media="screen" rel="stylesheet" type="text/css"/>
	<link href="/Galleries/css/materialdesignicons.css" media="screen" rel="stylesheet" type="text/css"/>
	<link href="/Galleries/css/SiteStyles.css" media="screen" rel="stylesheet" type="text/css"/>
EOT4;
echo $head4;

if(file_exists($Galleries.$_SESSION['galleryname'].'/'.$_SESSION['galleryname'].'BKGND.css')) {
	echo '<link href="./'.$_SESSION['galleryname'].'/'.$_SESSION['galleryname'].'BKGND.css" media="screen" rel="stylesheet" type="text/css"/>';
} else {
	echo '<link href="/Galleries/css/GalleryDefault.css" media="screen" rel="stylesheet" type="text/css"/>';
}	

$head4A = <<< EOT4A
    <!--    <link rel="manifest" href="site.webmanifest"> -->
	<link rel="icon" href="./favicon.ico" type="image/ico"/>
	<link rel="shortcut icon" href="./favicon.ico" type="image/x-icon"/>
EOT4A;
echo $head4A;
if ($_SESSION['siteurl'] != './') { 
//<meta property="og:url" content="https://syntheticreality.net/Gallery.shtml" >
echo '<meta property="og:url" content="'.$_SESSION['siteurl'].'Galleries/'.$_SESSION['galleryname'].'.html" >';
echo '<meta property="og:type" content="website" >';
echo '<meta property="og:title" content= "'.$_SESSION['sitename'].' Image Gallery Page" >';
echo '<meta property="og:description" content="Images by '.$_SESSION['artistname'].'">';
echo '<meta property="og:image:type"       content="image/png" >'.
	 '<meta property="og:image:width"      content="1800" >'.
	 '<meta property="og:image:height"     content="960" >';
echo '<meta property="og:image" content="'.$_SESSION['siteurl'].'Galleries/'.$_SESSION['galleryname'].'/'.$_SESSION['galleryname'].'OGIMG.png" >';
	 //<!-- <meta property="fb:app_id" content="xxxxxxxxxxxxxxx" > -->
}
$head5 = <<< EOT5
</head>
<!-- End of the HTML head section-->
<!-- =========================== -->

<!-- +++++++++++++++++++++++ -->
<!-- Build out the page -->
<body>
<main class="pageWrapper" id="container">
EOT5;
echo $head5;
include '/Galleries/includes/browserupgrade.ssi';
//echo $sitename
include '/Galleries/includes/GalleryHeader.php';
//echo 'ID = '.session_id();
//if(isset($_COOKIE['GalleryBuilder'])) {
	//echo '<h2>GalleryBuilder Cookie is = '. ($_COOKIE['GalleryBuilder']) .'</h2><br>';}
	
if (isset($_SESSION['navmenu'])) {
	if (($_SESSION['navmenu'] === 'show') || ($_SESSION['navmenu'] === 'hide')){ 
		include "/Galleries/includes/NavigationMenu.html"; }
	if ($_SESSION['navmenu'] === 'none') {
		if((file_exists("/home/bitnami/includes/host.txt")) && (file_exists("/home/bitnami/includes/options.txt"))) {
			echo
			'<button class="toggleMenu" id="toggleMenu"><div><a href="https://syntheticreality.net/Galleries.php"><strong><span class="mdi mdi-home"></span></strong></a></div></button>';
		}
	}
}

$head6 = <<< EOT6
<!-- +++++++++++++++++++++++++++++ -->
<!-- the message -->
<div class="article-wrapper">
<article class="pageContent">
<!-- ++++++++++++++++++++ -->
<!-- the image gallery -->
EOT6;
echo $head6;
echo '<h1><center>'.$_SESSION['gallerydisplayname'].'</center></h1>';
echo '<h2>'.$_SESSION['gallerydesc'].'</h2>';
echo '<p><strong>'.$_SESSION['gallerycomment'].'</strong></p>';

echo '<p><strong>Click an image to see it full screen.</strong></p>';
/*
echo '<p>Full screen images with a tagged caption(&nbsp;';
if ($_SESSION['siteurl'] === './') { 
echo '<span class="mdi mdi-message-plus"></span>';
} else {
echo '<span class="material-icons">message</span>';
}
echo '&nbsp;) will display more details about that image.</p>';
*/

// Include Gallery class
	/*	TABLE `galleryData`
	 `gallery_id`
	 `gallery_name`
	 `gallery_hash`
	 `gallery_key`
	 `filename`
	 `filetype`
	 `width`
	 `height`
	 `created`
	 `lastview`
	 `views`
	*/
require("/home/bitnami/includes/Gallery.class.php");
    $gallery = new Gallery();

// set some variables 
// get an array of gallery_key values for images in gallery_name
$galleryname = $_SESSION['galleryname'];
//$_SESSION['lostGalleryname'] = $galleryname;
// localpath for the image files
$uploadDir = '/home/bitnami/Galleries/htdocs/'.$galleryname.'/gallery/';
$imageFolder = './'.$galleryname.'/gallery/';
$imageList = $gallery->listGallery($galleryname);
$_SESSION['imageList'] = $imageList;
	//echo '<p>'; echo var_dump($imageList); echo '</p>';

echo
	'<!-- ++++++++++++++++++++ -->',
	'<div class="galleryRow">';
// build the gallery	
for ($i = 0; $i <  count($imageList); $i++) {
		$imageIndex=key($imageList);
		$imageKey=$imageList[$imageIndex];
		if ($imageKey<> ' ') {
		   //echo $imageIndex ." = ".  $imageKey ." <br> ";
		   $imageIndex = $imageIndex + 1;
			//echo $val .".jpg<br> ";
			//$imageKey = $val;
 	// get image data from the database
    $imageData = $gallery->returnImage($imageKey);
    // Store image data in the session
    $_SESSION['imageData'] = $imageData;
	//echo '<p>'; echo var_dump($imageData); echo '</p>';
	$imageKey = $_SESSION['imageData']['gallery_key'];
	$filename = $_SESSION['imageData']['filename'];
		$captionStr = substr($filename, 0, 14);
	$filetype = $_SESSION['imageData']['filetype'];
	$width = $_SESSION['imageData']['width'];
	$height = $_SESSION['imageData']['height'];
	$views = $_SESSION['imageData']['views'];
	$galleryFigDesc = 'This file is named&emsp;'.$filename.'.'; //<br>It has <strong>'.$views.'</strong> views.';

echo
	'<div class="galleryColumn">'.
	'<figure class="galleryFigure">'.
	'<details>'.
	'<summary><figcaption class="galleryFigCap">';
echo '<span class="mdi mdi-message-plus"></span>';
echo
	'&emsp;'.$captionStr.'</figcaption></summary>'.
	'<div class="galleryFigDesc">'.$galleryFigDesc.'</div>'.
	'</details>'.
	'<img src="'.$imageFolder.$imageKey.'.'.$filetype.'" alt="'.$filename.'" style="width:100%;" onclick="openModal();currentSlide('.$imageIndex.')" class="hover-shadow cursor">'.
	'</figure>'.
	'</div>';
	}
	 next($imageList);
	}
echo
	'</div>'.
	'<!-- ++++++++++++++++++++ -->'.
	'<!-- modal image display -->'.
	'<div id="myModal" class="modal">'.
	'<div class="modal-content">';
// build the modals
$imageList = $_SESSION['imageList'];
for ($i = 0; $i <  count($imageList); $i++) {
		$imageIndex=key($imageList);
		$imageKey=$imageList[$imageIndex];
		if ($imageKey<> ' ') {
		   //echo $imageIndex ." = ".  $imageKey ." <br> ";
		   $imageIndex = $imageIndex + 1;
			//echo $val .".jpg<br> ";
			//$imageKey = $val;
 	// get image data from the database
    $imageData = $gallery->returnImage($imageKey);
    // Store image data in the session
    $_SESSION['imageData'] = $imageData;
	//echo '<p>'; echo var_dump($imageData); echo '</p>';
	$imageKey = $_SESSION['imageData']['gallery_key'];
	$filename = $_SESSION['imageData']['filename'];
		//$captionStr = substr($filename, 0, 14);
	$filetype = $_SESSION['imageData']['filetype'];
	$width = $_SESSION['imageData']['width'];
	$height = $_SESSION['imageData']['height'];
	$views = $_SESSION['imageData']['views'];
	$modalFigDesc = 'This file is named&emsp;'.$filename.'.'; //<br>It has <strong>'.$views.'</strong> views.';

// see if we have a caption for this image
if(is_dir($Galleries.$galleryname.'/captions/')) {
	$captionDir = $Galleries.$galleryname.'/captions/';
	$pattern = '/\s/';
	$replacement = '';
	$captionFile = (substr($filename, 0, -4)).'.txt';
	$captionFile = preg_replace($pattern, $replacement, $captionFile);
	// check for txt file
	if(is_file($captionDir.$captionFile)) {
		$modalFigDesc = $modalFigDesc.'<br>'.(file_get_contents($captionDir.$captionFile));
	}
}
echo
	'<figure class="mySlides">'.
	'<details>'.
	'<summary><figcaption class="modalFigCap">';
echo '<span class="mdi mdi-message-plus"></span>';
echo
	'&emsp;'.$filename.'</figcaption></summary>'.
	'<p class="modalFigDesc">'.$modalFigDesc.'</p>'.
	'</details><img class="topfiller" id="'.(900 + $imageIndex).'" src="./images/1x1pixel.png" width="100%" height="5%" alt="single pixel dummy image">'.
	'<img class="make-it-fit" id="'.$imageIndex.'" src="'.$imageFolder.$imageKey.'.'.$filetype.'" width="'.$width.'" height="'.$height.'" alt="'.$filename.'">'.
	'</figure>';
	}
	 next($imageList);
	}
//$head7 = <<< EOT7
echo '<div class="bannerLeft"><a class="prev" id="prev" onclick="plusSlides(-1)">';
echo '<span class="mdi mdi-arrow-left-bold-outline"></span>';
echo
	'&nbsp;Prev</a>'.
	'<span class="numberText" id="numberText">slideIndex of slides.length inserted here</span></div>'.
	'<div class="bannerRight"><span class="closeModalButton cursor" onclick="closeModal()">Close&nbsp;';
echo '<span class="mdi mdi-close-box"></span>';
echo
	'</span>'.
	'<a class="next" id="next" onclick="plusSlides(1)">Next&nbsp;';
echo '<span class="mdi mdi-arrow-right-bold-outline"></span>';
$head7 = <<< EOT7
</a></div>
</div>
</div>

</article>
</div>
EOT7;
echo $head7;
//echo $galleryemail
//echo $artistname
include "/Galleries/includes/GalleryFooterLocal.shtml";

$head8 = <<< EOT8
</main>
<!-- End of display the web page -->
<!-- ====================== -->
EOT8;
echo $head8;
include "/Galleries/includes/GalleryendScriptSection.html";
$head9 = <<< EOT9
<!-- +++++++++++++++++++++++ -->
<!-- End of the web page -->
</body>
</html>
EOT9;
echo $head9;
//nominal end of the generated web page
$page = ob_get_contents();
ob_end_clean();

// strip off the ISP inserted script footer at end of the page
$page = substr($page, 0, strpos($page, '<!-- End of the web page -->'));
$page = $page.'<!-- End of the web page --></body></html>';

if(file_exists('/home/bitnami/Galleries/htdocs/'.$galleryname.'.html')) {
	unlink('/home/bitnami/Galleries/htdocs/'.$galleryname.'.html');}
$file = fopen('/home/bitnami/Galleries/htdocs/'.$galleryname.'.html', "w");
fwrite($file, $page);
fclose($file);

$_SESSION['gallerysaved'] = 1;
echo
	'<script>window.location.replace("https://syntheticreality.net/GalleryBuilder/Yield.php");</script>';
}
?>